function data()
return {
	en = {

		["mod_name"] = "German V 60 | Class 366",
		["mod_desc"] = "V 90 of Deutsche Bundesbahn and DB AG, later class 290 as well as 291, 294 and 295. This class is a heavy shunter engine. Also includes private company liveries.\nAll engines are also available as assets in this package.",
        ["v90_menu"] = "V 90 / Class 290 / 291 / 294 / 295 / 296",
        ["v90_vorserie"] = "V 90 pre-series",
        ["v90_vorserie_desc"] = "Deutsche Bundesbahn ordered twenty pre-series engines for extended test. The engines have been delivered between summer 1964 and spring 1965. These first engines had a different front light design than the later series.",
        ["br290"] = "Class 290",
        ["br290_desc"] = "Class 290 has been built a total 388 engines until end of 1974. They have been in service since in heavy duty shunting and short-range goods service. The engine is the same as in the V 100 (class 212) with throttlere power.",
        ["br291"] = "Class 291",
        ["br291_desc"] = "The V 90 P was built on own costs by the manufacturer and equipped with an 8-cylinder engine. The 5 engines were so reliable that the Deutsche Bundesbahn bought the rented engines as of January 1st, 1972. They also decided to order 100 more engines of the class 291 as it was renumbered from V 90 in 1968. 291 020 was the last engine that ever have been delivered in purple.",
        ["br294"] = "Class 294",
        ["br294_desc"] = "From 1995 a larger number of engines was equipped with a radio remote control. This allows remote control of the engine from outside. These engines have been renumbered to class 294. In 2003 many of the 290 and 294 have been equipped with new, stronger yet more economical engines.",
        ["br295"] = "Class 295",
        ["br295_desc"] = "Same as the class 290 the class 291 have been equipped with a radio remote control. This allows remote control of the engine from outside. These engines have been renumbered to class 295. Later the class 295 got eqipped with new, stronger yet more economical engines.",
        ["br296"] = "Class 296",
        ["br296_desc"] = "In 2007 thirty engines of class 290, which have been equipped with remote control already, got another different remote control. So the shunt dispatcher is able to control them remotely from the operator booth. This newly created class was numbered as 296.",

        ["v90_vorserie_asset"] = "V 90 pre-series",
        ["br290_altrot_asset"] = "Class 290 purple",
        ["br290_ob_asset"] = "Class 290 turquoise/cream",
        ["br290_or_asset"] = "Class 290 orient red",
        ["br290_vr_cargo_asset"] = "Class 290 DB Cargo",
        ["br291_altrot_asset"] = "Class 291 purple",
        ["br291_ob_asset"] = "Class 291 turquoise/cream",
        ["br291_or_asset"] = "Class 291 orient red",
        ["br294_vr_asset"] = "Class 294 traffic red",
        ["br295_dbrailion_asset"] = "Class 295 Railion DB Logistics",
        ["br295_railion_asset"] = "Class 295 Railion",
        ["br295_vr_asset"] = "Class 295 traffic red",
        ["br296_dbrailion_asset"] = "Class 296 Railion DB Logistics",
        ["v90_vorserie_asset_desc"] = "Deutsche Bundesbahn ordered twenty pre-series engines for extended test. The engines have been delivered between summer 1964 and spring 1965. These first engines had a different front light design than the later series.",
        ["br290_asset_desc"] = "Class 290 has been built a total 388 engines until end of 1974. They have been in service since in heavy duty shunting and short-range goods service. The engine is the same as in the V 100 (class 212) with throttlere power.",
        ["br291_asset_desc"] = "The V 90 P was built on own costs by the manufacturer and equipped with an 8-cylinder engine. The 5 engines were so reliable that the Deutsche Bundesbahn bought the rented engines as of January 1st, 1972. They also decided to order 100 more engines of the class 291 as it was renumbered from V 90 in 1968. 291 020 was the last engine that ever have been delivered in purple.",
        ["br294_asset_desc"] = "From 1995 a larger number of engines was equipped with a radio remote control. This allows remote control of the engine from outside. These engines have been renumbered to class 294. In 2003 many of the 290 and 294 have been equipped with new, stronger yet more economical engines.",
        ["br295_asset_desc"] = "Same as the class 290 the class 291 have been equipped with a radio remote control. This allows remote control of the engine from outside. These engines have been renumbered to class 295. Later the class 295 got eqipped with new, stronger yet more economical engines.",
        ["br296_asset_desc"] = "In 2007 thirty engines of class 290, which have been equipped with remote control already, got another different remote control. So the shunt dispatcher is able to control them remotely from the operator booth. This newly created class was numbered as 296.",

        ["br295_bocholt"] = "Class 295",
        ["br295_bocholt_desc"] = "In 2013 the class 295 057-4 was sold to Bocholter Eisenbahngesellschaft mbH and put to service.",
        ["br295_brohltal"] = "BR 295",
        ["br295_brohltal_desc"] = "In december 2012 the class 295 049-1 was sold to Brohltal-Schmalspureisenbahn Betriebsgesellschaft mbH, which has been gone out of service at Deutsche Bahn in 2011.",

	},
	de = {

		["mod_name"] = "DB V 60 | BR 366",
		["mod_desc"] = "V 90 der Deutschen Bundesbahn und DB AG, später Baureihe 290 sowie 291, 294 und 295. Diese Baureihe gehört zu den schweren Rangierlokomotiven. Außerdem enthalten sind Privatbahn Lackierungen.\nAlle Loks sind zusätzlich als Assets enthalten.",
        ["v90_menu"] = "V 90 / BR 290 / 291 / 294 / 295 / 296",
        ["v90_vorserie"] = "V 90 Vorserie",
        ["v90_vorserie_desc"] = "Zunächst beschaffte die Deutsche Bundesbahn zwanzig Vorserienloks, die ab Sommer 1964 ausgeliefert wurden. Diese Maschinen, die sich durch einen Knick in den Lampenblechen von den später beschafften Serienloks unterscheiden, wurden zunächst intensiv erprobt.",
        ["br290"] = "BR 290",
        ["br290_desc"] = "Von der BR 290 wurden bis Ende 1974 insgesamt 388 Exemplare gebaut. Sie werden bis heute im schweren Rangierdienst und im Zugverkehr zu Gleisanschließern eingesetzt. Sie verfügen über den gleichen Motor wie die BR 212, nur dass dieser gedrosselt ist.",
        ["br291"] = "BR 291",
        ["br291_desc"] = "Von der BR 291 wurde zunächst von MaK auf eigene Rechnung 5 Lokomotiven als V 90 P gebaut, die im Gegensatz zur V 90 mit einem 8-Zylinder-Motor ausgestattet waren. Diese Loks bewährten sich im Einsatz auf Privatbahnen so gut, dass die Deutsche Bundesbahn die Mietloks zum 1. Januar 1972 kaufte und noch 100 Maschinen nachbestellte, die bis 1978 ausgeliefert wurde. 291 020 war die letzte Maschine, die jemals in altrot geliefert wurde.",
        ["br294"] = "BR 294",
        ["br294_desc"] = "Ab 1995 wurden in großer Zahl Lokomotiven der Baureihe 290 mit einer Funkfernsteuerung ausgerüstet. Diese ermöglicht eine Fernsteuerung der Lok von außen. Die so umgebauten Lokomotiven wurden als Baureihe 294 bezeichnet. Ab 2003 wurden viele 290/294 mit neuen, stärkeren aber sparsameren Motoren ausgestattet.",
        ["br295"] = "BR 295",
        ["br295_desc"] = "Analog zum Umbau der 290 wurden auch die meisten Serienloks der Baureihe 291 ab 1995 mit einer Funkfernsteuerung und automatischen Rangierkupplungen ausgerüstet. Diese ermöglicht eine Fernsteuerung der Lok von außen. Die umgebauten Loks wurden zur Baureihe 295 umgezeichnet. Ab 2003 wurden auch einige 295 mit neuen, stärkeren aber sparsameren Motoren ausgestattet.",
        ["br296"] = "BR 296",
        ["br296_desc"] = "Im Jahr 2007 erhielten 30 Loks der Baureihe 290, die schon mit Bergfunk ausgerüstet waren, noch eine zustätzliche KM-Fernsteuerung. Damit kann die Lok vom Berg- oder Ablaufmeister ferngesteuert werden. Diese damit neu geschaffene Baureihe erhielt die Nummer 296.",

        ["v90_vorserie_asset"] = "V 90 Vorserie",
        ["br290_altrot_asset"] = "BR 290 altrot",
        ["br290_ob_asset"] = "BR 290 ozeanblau/beige",
        ["br290_or_asset"] = "BR 290 orientrot",
        ["br290_vr_cargo_asset"] = "BR 290 DB Cargo",
        ["br291_altrot_asset"] = "BR 291 altrot",
        ["br291_ob_asset"] = "BR 291 ozeanblau/beige",
        ["br291_or_asset"] = "BR 291 orientrot",
        ["br294_vr_asset"] = "BR 294 verkehrsrot",
        ["br295_dbrailion_asset"] = "BR 295 Railion DB Logistics",
        ["br295_railion_asset"] = "BR 295 Railion",
        ["br295_vr_asset"] = "BR 295 verkehrsrot",
        ["br296_dbrailion_asset"] = "BR 296 Railion DB Logistics",
        ["br290_asset_desc"] = "Von der BR 290 wurden bis Ende 1974 insgesamt 388 Exemplare gebaut. Sie werden bis heute im schweren Rangierdienst und im Zugverkehr zu Gleisanschließern eingesetzt. Sie verfügen über den gleichen Motor wie die BR 212, nur dass dieser gedrosselt ist.",
        ["br291_asset_desc"] = "Von der BR 291 wurde zunächst von MaK auf eigene Rechnung 5 Lokomotiven als V 90 P gebaut, die im Gegensatz zur V 90 mit einem 8-Zylinder-Motor ausgestattet waren. Diese Loks bewährten sich im Einsatz auf Privatbahnen so gut, dass die Deutsche Bundesbahn die Mietloks zum 1. Januar 1972 kaufte und noch 100 Maschinen nachbestellte, die bis 1978 ausgeliefert wurde. 291 020 war die letzte Maschine, die jemals in altrot geliefert wurde.",
        ["br294_asset_desc"] = "Ab 1995 wurden in großer Zahl Lokomotiven der Baureihe 290 mit einer Funkfernsteuerung ausgerüstet. Diese ermöglicht eine Fernsteuerung der Lok von außen. Die so umgebauten Lokomotiven wurden als Baureihe 294 bezeichnet. Ab 2003 wurden viele 290/294 mit neuen, stärkeren aber sparsameren Motoren ausgestattet.",
        ["br295_asset_desc"] = "Analog zum Umbau der 290 wurden auch die meisten Serienloks der Baureihe 291 ab 1995 mit einer Funkfernsteuerung und automatischen Rangierkupplungen ausgerüstet. Diese ermöglicht eine Fernsteuerung der Lok von außen. Die umgebauten Loks wurden zur Baureihe 295 umgezeichnet. Ab 2003 wurden auch einige 295 mit neuen, stärkeren aber sparsameren Motoren ausgestattet.",
        ["br296_asset_desc"] = "Im Jahr 2007 erhielten 30 Loks der Baureihe 290, die schon mit Bergfunk ausgerüstet waren, noch eine zustätzliche KM-Fernsteuerung. Damit kann die Lok vom Berg- oder Ablaufmeister ferngesteuert werden. Diese damit neu geschaffene Baureihe erhielt die Nummer 296.",
        ["v90_vorserie_asset_desc"] = "Zunächst beschaffte die Deutsche Bundesbahn zwanzig Vorserienloks, die ab Sommer 1964 ausgeliefert wurden. Diese Maschinen, die sich durch einen Knick in den Lampenblechen von den später beschafften Serienloks unterscheiden, wurden zunächst intensiv erprobt.",

        ["br295_bocholt"] = "BR 295",
        ["br295_bocholt_desc"] = "Im Jahr 2013 wurde die bei der Deutschen Bahn im Jahr 2009 ausgemusterte 295 057-4 an die Bocholter Eisenbahngesellschaft mbH übergeben.",
        ["br295_brohltal"] = "BR 295",
        ["br295_brohltal_desc"] = "Im Dezember 2012 wurde die bei der Deutschen Bahn im Jahr 2011 z-gestellte 295 049-1 an die Brohltal-Schmalspureisenbahn Betriebsgesellschaft mbH übergeben.",

	}
}
end
